version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./:/var/www/html/erp
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "Adr4r!"
      MYSQL_DATABASE: "root"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: